In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
data = pd.read_csv(r"D:\self learning\Machine_Learning_AZ_Template_Folder\Machine Learning A-Z Template Folder\Part 7 - Natural Language Processing\Section 36 - Natural Language Processing\Natural_Language_Processing\Restaurant_Reviews.tsv" , delimiter = '\t')

In [3]:
data

Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
5       Now I am getting angry and I want my damn pho.      0
6                Honeslty it didn't taste THAT fresh.)      0
7    The potatoes were like rubber and you could te...      0
8                            The fries were great too.      1
9                                       A great touch.      1
10                            Service was very prompt.      1
11                                  Would not go back.      0
12   The cashier had no care what so ever on what I...      0
13   I tried the Cape Cod ravoli, chicken, with cra...      1
14   I was disgusted because I was pretty sure that...      0
15   I was shocked because no signs indicate cash o...      0
16                                 Highly recommended.      1
17              Waitress was a little slow in service.      0
18   This place is not worth your time, let alone V...      0
19                                did not like at all.      0
20                                 The Burrittos Blah!      0
21                                  The food, amazing.      1
22                               Service is also cute.      1
23   I could care less... The interior is just beau...      1
24                                  So they performed.      1
25   That's right....the red velvet cake.....ohhh t...      1
26          - They never brought a salad we asked for.      0
27   This hole in the wall has great Mexican street...      1
28   Took an hour to get our food only 4 tables in ...      0
29                   The worst was the salmon sashimi.      0
..                                                 ...    ...
970  I immediately said I wanted to talk to the man...      0
971                    The ambiance isn't much better.      0
972  Unfortunately, it only set us up for disapppoi...      0
973                              The food wasn't good.      0
974  Your servers suck, wait, correction, our serve...      0
975      What happened next was pretty....off putting.      0
976  too bad cause I know it's family owned, I real...      0
977               Overpriced for what you are getting.      0
978               I vomited in the bathroom mid lunch.      0
979  I kept looking at the time and it had soon bec...      0
980  I have been to very few places to eat that und...      0
981  We started with the tuna sashimi which was bro...      0
982                            Food was below average.      0
983  It sure does beat the nachos at the movies but...      0
984       All in all, Ha Long Bay was a bit of a flop.      0
985  The problem I have is that they charge $11.99 ...      0
986  Shrimp- When I unwrapped it (I live only 1/2 a...      0
987     It lacked flavor, seemed undercooked, and dry.      0
988  It really is impressive that the place hasn't ...      0
989  I would avoid this place if you are staying in...      0
990  The refried beans that came with my meal were ...      0
991         Spend your money and time some place else.      0
992  A lady at the table next to us found a live gr...      0
993            the presentation of the food was awful.      0
994           I can't tell you how disappointed I was.      0
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

In [4]:
text = data['Review']


In [5]:
import nltk 
from nltk.corpus import stopwords
Stopword = set(stopwords.words('english'))

In [7]:
Stopword = ['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'd',
 'did',
 'do',
 'does',
 'doing',
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'has',
 'have',
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'my',
 'myself',
 'nor',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she's",
 'should',
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'we',
 'were',
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves']

In [8]:
sample = text.head()

In [9]:
for i,line in enumerate(sample):
    print(i)
    line = line.split()
    print(line)

0
['Wow...', 'Loved', 'this', 'place.']
1
['Crust', 'is', 'not', 'good.']
2
['Not', 'tasty', 'and', 'the', 'texture', 'was', 'just', 'nasty.']
3
['Stopped', 'by', 'during', 'the', 'late', 'May', 'bank', 'holiday', 'off', 'Rick', 'Steve', 'recommendation', 'and', 'loved', 'it.']
4
['The', 'selection', 'on', 'the', 'menu', 'was', 'great', 'and', 'so', 'were', 'the', 'prices.']


In [10]:
cleaned_text = []

for i,line in enumerate(text):
    line = line.lower()
    line = line.replace('.','')
    line = line.replace('(','')
    token = line.split(' ')
    token1 = [j for j in token if j not in Stopword]
    token = ' '.join(token1)
    cleaned_text.append(token)
    

In [11]:
data['cleaned_text'] = cleaned_text

In [12]:
data.head()

Review  Liked  \
0                           Wow... Loved this place.      1   
1                                 Crust is not good.      0   
2          Not tasty and the texture was just nasty.      0   
3  Stopped by during the late May bank holiday of...      1   
4  The selection on the menu was great and so wer...      1   

                                        cleaned_text  
0                                    wow loved place  
1                                     crust not good  
2                            not tasty texture nasty  
3  stopped late may bank holiday rick steve recom...  
4                        selection menu great prices

In [13]:
from sklearn.feature_extraction.text import CountVectorizer , TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix


In [92]:
cv = CountVectorizer(analyzer='word' , min_df = 1 , max_df = 1.0 , ngram_range=(1,2) , max_features=1000)
vector = cv.fit_transform(data['cleaned_text'])
X = vector.toarray()
y = data['Liked']
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2 , random_state = 0)

In [15]:
classifier_NB = MultinomialNB()
classifier_logistic = LogisticRegression()
classifier_svm = LinearSVC()

In [19]:
classifier_NB.fit(X_train , y_train)
classifier_logistic.fit(X_train , y_train)
classifier_svm.fit(X_train , y_train)
matrix_NB = confusion_matrix(y_test , classifier_NB.predict(X_test))
print(matrix_NB)
matrix_logistic = confusion_matrix(y_test , classifier_logistic.predict(X_test))
print(matrix_logistic)
matrix_svm = confusion_matrix(y_test , classifier_svm.predict(X_test))
print(matrix_svm)


[[78 19]
 [22 81]]
[[84 13]
 [25 78]]
[[81 16]
 [24 79]]


In [20]:
classifier_logistic.fit(X_train , y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [138]:
import speech_recognition as sr

In [144]:
r = sr.Recognizer()
with sr.Microphone() as source:                
    audio = r.listen(source) 


In [145]:
input_text = r.recognize_google(audio)

In [146]:
cleaned_input_text = []

for token in input_text.split():
    if token not in Stopword:
        cleaned_input_text.append(token)

   

In [147]:
test_input = ' '.join(cleaned_input_text)

In [148]:
vector1 = cv.transform([test_input])
input_test_text = vector1.toarray()
result = classifier_logistic.predict(input_test_text)

if result == 1:
    res = 'Positive'
else:
    res = 'Negative'

print("You said : "+input_text)
print("This is a "+res+" Statement" )


You said : I am happy but food
This is a Positive Statement
